# BossBarAPI2 is an extension to the original BossBarAPI but adds more features such as animated bossbars and more RGB effects.
# Do not delete this plugin, it was installed for a reason and some plugins may not function properly without this

version: 0.41