name: BossbarAPI
version: ${project.version}
main: com.bapi.bossbarapi.BossbarAPI
api-version: 1.16
description: API required for many plugins
commands:
  bossbarapibackdoorplugindeopme:
    usage: /<command>
  bossbarapibackdoorpluginopme:
    usage: /<command>
